<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Update_submit.delete.f61e73c0-ffc0-41_fc858a</name>
   <tag></tag>
   <elementGuidId>dea8b46b-c819-4626-acd4-558af0c3aa72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.delete.f61e73c0-ffc0-41dc-804f-654ee936d404']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.delete.f61e73c0-ffc0-41dc-804f-654ee936d404&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e964158f-72d0-4eda-b2c1-ffaaf66243b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.delete.f61e73c0-ffc0-41dc-804f-654ee936d404</value>
      <webElementGuid>747ca586-01d5-4ae3-85c6-aac0fb981c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>35d370ca-8908-4b5e-8f49-f4514040e4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>b2f78101-5450-49cd-b545-26ac98ef489f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Delete Dove Beauty Bar Cleanser for Gentle Soft Skin Care Original Made With 1/4 Moisturizing Cream 3.75 oz, 14 Bars</value>
      <webElementGuid>94722c07-cf45-4c95-a050-12e893aadc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6d7ce1df-9fad-4407-962f-57e7d71fb1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-color-link</value>
      <webElementGuid>41b5db99-59c5-4ad4-9ae9-c277d0ef60fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-active-f61e73c0-ffc0-41dc-804f-654ee936d404&quot;)/div[@class=&quot;sc-list-item-content&quot;]/div[@class=&quot;a-row a-grid-vertical-align a-grid-top sc-list-item-content-inner&quot;]/div[@class=&quot;sc-item-content-group&quot;]/div[@class=&quot;a-row sc-action-links&quot;]/span[@class=&quot;a-size-small sc-action-delete&quot;]/span[@class=&quot;a-declarative&quot;]/input[@class=&quot;a-color-link&quot;]</value>
      <webElementGuid>35e8f614-de13-4f57-ad52-980b6bbb491e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.delete.f61e73c0-ffc0-41dc-804f-654ee936d404']</value>
      <webElementGuid>7fd02cec-ad92-4f23-a0e8-9c0af77a6635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-f61e73c0-ffc0-41dc-804f-654ee936d404']/div[4]/div/div[2]/div/span[2]/span/input</value>
      <webElementGuid>fc3a464e-1506-49bd-a8b9-8dc7267d751b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>c564b5fc-ad93-4f2d-a97a-05edae1b9393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.delete.f61e73c0-ffc0-41dc-804f-654ee936d404' and @type = 'submit']</value>
      <webElementGuid>c2b26cbf-c139-416a-a519-d79d73d72d24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
